- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install podman and machinectl commands
      dnf:
        name:
          - podman
          - systemd-container

    - name: Create podman user
      user:
        name: podman
      register: user

    - name: Enable lingering for user
      command:
        cmd: loginctl enable-linger {{ user.name }}
        creates: "/var/lib/systemd/linger/{{ user.name }}"

    - name: Enable logging for systemd user units
      # see https://unix.stackexchange.com/a/486566/365795
      community.general.ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: Storage
        value: persistent
        no_extra_spaces: true
      register: journald

    - name: Restart journald
      command:
        cmd: systemctl restart systemd-journald
      when: journald.changed

    - name: Create user service directory
      file:
        path: /home/{{ user.name }}/.config/systemd/user/
        state: directory
      become_user: "{{ user.name }}" # required to get ownership/permissions on .config/ right

    - name: Create service
      template:
        src: apache.service.j2
        dest: /home/{{ user.name }}/.config/systemd/user/apache.service # TODO: not sure if this is best path?
      become_user: "{{ user.name }}"
      register: apache_service

    - name: Start service
      systemd:
        name: apache
        state: started
        enabled: yes
        daemon_reload: "{{ apache_service.changed }}"
        scope: user
      become_user: "{{ user.name }}"

    - name: Check apache works
      command:
        cmd: curl localhost:8080
      register: curl
      changed_when: false

    - debug:
        var: curl.stdout
