- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install podman
      dnf:
        name: podman
    - name: Create podman user
      user:
        name: podman
    - name: Create service
      template:
        src: apache.service.j2
        dest: /etc/systemd/system/apache.service
    - name: Start service
      systemd:
        name: apache
        state: started
